version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "YourPassword123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

  configurationapi:
    build:
      context: .
      dockerfile: ConfigurationAPI/Dockerfile
    ports:
      - ":80"
      - ":443"
    depends_on:
      - sqlserver
      - servicea
      - serviceb
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=TestDatabase;User Id=sa;Password=YourPassword123;

  servicea:
    build:
      context: .
      dockerfile: Service-A/Dockerfile
    ports:
      - ":80"
      - ":443"
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=TestDatabase;User Id=sa;Password=YourPassword123;

  serviceb:
    build:
      context: .
      dockerfile: Service-B/Dockerfile
    ports:
      - ":80"
      - ":443"
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=TestDatabase;User Id=sa;Password=YourPassword123;
